
export const EMAIL_EXPIRATION_NOTIFICATION_QUEUE = 'EMAIL_EXPIRATION_NOTIFICATION_QUEUE';

export const WEEK_BEFORE_NOTIFICATION = 'WEEK_BEFORE_NOTIFICATION';
export const EXPIRATION_NOTIFICATION = 'EXPIRATION_NOTIFICATION';
export const EXPORT_EXPIRATION = 'EXPORT_EXPIRATION';
