export const STAGE_UPLOAD = 'STAGE_UPLOAD';
export const STAGE_CONFIGURE_FIELDS = 'STAGE_CONFIGURE_FIELDS';
export const STAGE_IMPORTED = 'STAGE_IMPORTED';

export const COLUMN_NAME = 'COLUMN_NAME'; // personas name
export const COLUMN_IFI_KEY = 'COLUMN_KEY';
export const COLUMN_IFI_VALUE = 'COLUMN_VALUE';
export const COLUMN_MBOX = 'COLUMN_MBOX';
export const COLUMN_MBOXSHA1SUM = 'COLUMN_MBOXSHA1SUM';
export const COLUMN_OPENID = 'COLUMN_OPENID';
export const COLUMN_ACCOUNT_KEY = 'COLUMN_ACCOUNT_KEY';
export const COLUMN_ACCOUNT_VALUE = 'COLUMN_ACCOUNT_VALUE';

export const COLUMN_AGENT_DATA = 'COLUMN_AGANT_DATA';
export const COLUMN_AGENT_DATA_KEY = 'COLUMN_AGENT_DATA_KEY'; // optional key for COLUMMNT_AGENT_DATA, otherwise csv header will be used.

export const COLUMN_TYPES = [
  COLUMN_NAME,
  COLUMN_IFI_KEY,
  COLUMN_IFI_VALUE,
  COLUMN_MBOX,
  COLUMN_MBOXSHA1SUM,
  COLUMN_OPENID,
  COLUMN_ACCOUNT_KEY,
  COLUMN_ACCOUNT_VALUE,
  COLUMN_AGENT_DATA,
  COLUMN_AGENT_DATA_KEY
];

export const RELATED_COLUMN_MAP = {
  [COLUMN_IFI_KEY]: {
    related: [COLUMN_IFI_VALUE]
  },
  [COLUMN_ACCOUNT_KEY]: {
    related: [COLUMN_ACCOUNT_VALUE]
  },
  [COLUMN_AGENT_DATA_KEY]: {
    keyOptional: true, // if key isn't set, use the column header.
    related: [COLUMN_AGENT_DATA]
  }
};

export const IDENTIFIER_KEYS = [
  COLUMN_IFI_KEY,
  COLUMN_MBOX,
  COLUMN_MBOXSHA1SUM,
  COLUMN_OPENID,
  COLUMN_ACCOUNT_KEY
];
