export const VISUALISE_AXES_PREFIX = 'axes';
export const MAX_CUSTOM_COLORS = 7;

// Visualisation Types
export const LEADERBOARD = 'LEADERBOARD';
export const XVSY = 'XVSY';
export const STATEMENTS = 'STATEMENTS';
export const FREQUENCY = 'FREQUENCY';
export const COUNTER = 'COUNTER';
export const PIE = 'PIE';

export const TEMPLATE_ACTIVITY_OVER_TIME = 'TEMPLATE_ACTIVITY_OVER_TIME';
export const TEMPLATE_LAST_7_DAYS_STATEMENTS = 'TEMPLATE_LAST_7_DAYS_STATEMENTS';
export const TEMPLATE_MOST_ACTIVE_PEOPLE = 'TEMPLATE_MOST_ACTIVE_PEOPLE';
export const TEMPLATE_MOST_POPULAR_ACTIVITIES = 'TEMPLATE_MOST_POPULAR_ACTIVITIES';
export const TEMPLATE_MOST_POPULAR_VERBS = 'TEMPLATE_MOST_POPULAR_VERBS';
export const TEMPLATE_WEEKDAYS_ACTIVITY = 'TEMPLATE_WEEKDAYS_ACTIVITY';
export const TEMPLATE_CURATR_INTERACTIONS_VS_ENGAGEMENT = 'TEMPLATE_CURATR_INTERACTIONS_VS_ENGAGEMENT';
