export const VISUALISE_AXES_PREFIX = 'axes';
export const MAX_CUSTOM_COLORS = 7;
export const RESPONSE_ROWS_LIMIT = 10000;

// Visualisation Types
export const LEADERBOARD = 'LEADERBOARD';
export const XVSY = 'XVSY';
export const STATEMENTS = 'STATEMENTS';
export const FREQUENCY = 'FREQUENCY';
export const COUNTER = 'COUNTER';
export const PIE = 'PIE';

export const TEMPLATE_ACTIVITY_OVER_TIME = 'TEMPLATE_ACTIVITY_OVER_TIME';
export const TEMPLATE_LAST_7_DAYS_STATEMENTS = 'TEMPLATE_LAST_7_DAYS_STATEMENTS';
export const TEMPLATE_MOST_ACTIVE_PEOPLE = 'TEMPLATE_MOST_ACTIVE_PEOPLE';
export const TEMPLATE_MOST_POPULAR_ACTIVITIES = 'TEMPLATE_MOST_POPULAR_ACTIVITIES';
export const TEMPLATE_MOST_POPULAR_VERBS = 'TEMPLATE_MOST_POPULAR_VERBS';
export const TEMPLATE_WEEKDAYS_ACTIVITY = 'TEMPLATE_WEEKDAYS_ACTIVITY';
export const TEMPLATE_LEARNING_EXPERIENCE_TYPE = 'TEMPLATE_LEARNING_EXPERIENCE_TYPE';

export const TEMPLATE_STREAM_INTERACTIONS_VS_ENGAGEMENT = 'TEMPLATE_STREAM_INTERACTIONS_VS_ENGAGEMENT';
export const TEMPLATE_STREAM_COMMENT_COUNT = 'TEMPLATE_STREAM_COMMENT_COUNT';
export const TEMPLATE_STREAM_LEARNER_INTERACTIONS_BY_DATE_AND_VERB = 'TEMPLATE_STREAM_LEARNER_INTERACTIONS_BY_DATE_AND_VERB';
export const TEMPLATE_STREAM_USER_ENGAGEMENT_LEADERBOARD = 'TEMPLATE_STREAM_USER_ENGAGEMENT_LEADERBOARD';
export const TEMPLATE_STREAM_PROPORTION_OF_SOCIAL_INTERACTIONS = 'TEMPLATE_STREAM_PROPORTION_OF_SOCIAL_INTERACTIONS';
export const TEMPLATE_STREAM_ACTIVITIES_WITH_MOST_COMMENTS = 'TEMPLATE_STREAM_ACTIVITIES_WITH_MOST_COMMENTS';
